### ISSUE TITLE
Capistrano: Don't know how to build task 'pg_backup:dump:create' 

### ISSUE THREAD

**Issue by vzamanillo** [marcusg/pg_backup#8]
Version: 0.3.0

```
DEBUG [3163879a] 	rake aborted!

Don't know how to build task 'pg_backup:dump:create' (see --tasks)

 DEBUG [3163879a] 	/home/me/app/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/lib/bundler/cli/exec.rb:74:in `load'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/lib/bundler/cli/exec.rb:27:in `run'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/lib/bundler/cli.rb:332:in `exec'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/lib/bundler/cli.rb:20:in `dispatch'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/lib/bundler/cli.rb:11:in `start'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/exe/bundle:34:in `block in <top (required)>'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/home/me/.rvm/gems/ruby-2.3.1@pre/gems/bundler-1.13.3/exe/bundle:26:in `<top (required)>'
/home/me/.rvm/gems/ruby-2.3.1@pre/bin/bundle:22:in `load'
/home/me/.rvm/gems/ruby-2.3.1@pre/bin/bundle:22:in `<main>'

 DEBUG [3163879a] 	(See full trace by running task with --trace)
```

The deploy file:

```
server 'server', user: 'user', roles: %w(web app db)

set :rails_env, 'staging'

set :default_env, rails_env: fetch(:rails_env)

set :environment, fetch(:rails_env)

set :deploy_to, '/home/me/app'
set :branch, 'staging'
.....

# Flow
before 'deploy:starting', 'database:backup_list' # shows list of dumps in remote dir
before 'deploy:started',  'database:backup'

namespace :database do
  task :backup_list do
    invoke 'pg_backup:dump:list'
  end

  task :backup do
    invoke 'pg_backup:dump:create'
  end

  task :download_backup do
    invoke 'pg_backup:dump:download'
  end
end
```
Any ideas?

Thank you.

**Comment by marcusg** [comment]
Do you have ```require "pg_backup/integration/capistrano"``` in your Capfile? And you run ```bundle exec cap <env> pg_backup:dump:create```? Can you just check if the command runs without deploy?

**Comment by vzamanillo** [comment]
Hi Marcus!

Yes, I have the require in the Capfile.

If I run `bundle exec cap <env> pg_backup:dump:create` I have got the same error.

The `list` and `download` tasks works fine.

If I run `bundle exec cap --tasks` I can see the `pg_backup` tasks listed:

```
cap pg_backup:dump:create          # Create remote db dump
cap pg_backup:dump:download     # Download remote db dump
cap pg_backup:dump:list                # List remote db dumps
cap pg_backup:dump:load             # Loads the backup dump
cap pg_backup:dump:upload         # Upload latest db dump from (local) dump dir
```

**Comment by marcusg** [comment]
Hey @vzamanillo - can you please try to deploy your app without your cap hook
```before 'deploy:started',  'database:backup'```
Since ```pg_backup:dump:create``` uses a rake task which is not yet deployed on your remote server, it can't be found.

**Comment by vzamanillo** [comment]
I am trying with

```
before 'deploy:migrate', 'database:backup_list'
before 'deploy:migrate',   'database:backup'
after  'deploy:migrate',   'database:download_backup'
```

actually, but I am getting the same error.

In what stage the hooks should be called?

Thank you very much, Marcus!!

**Comment by marcusg** [comment]
No I mean just comment out the lines ```before xxx``` and ```after xxx```. Try to deploy your app normally so that pg_backup gem is installed on your remote server. *Then* you can try to enable the hooks again.

**Comment by vzamanillo** [comment]
I understand why the task is not found trying to create the backup at `before 'deploy:started'` stage in the capistrano flow but it should work before `deploy:migrate` because the migration is one step above of `deploy:bundle` so the `pg_backup`  gem should be installed and should be found, or maybe I am missing something

```
  deploy:updated
    [before]
      deploy:bundle
    [after]
      deploy:migrate
      deploy:compile_assets
      deploy:normalize_assets
```

**Comment by marcusg** [comment]
@vzamanillo sounds reasonable. Can you please attach the full capistrano output? I'll try your backup flow in one of my apps...

**Comment by marcusg** [comment]
@vzamanillo The following flow works in my setup without any problems:
```
# Flow
before 'deploy:starting', 'database:backup_list' # shows list of dumps in remote dir
before 'deploy:migrate',  'database:backup'

namespace :database do
  task :backup_list do
    invoke 'pg_backup:dump:list'
  end

  task :backup do
    invoke 'pg_backup:dump:create'
  end

  task :download_backup do
    invoke 'pg_backup:dump:download'
  end
end
```

**Comment by vzamanillo** [comment]
Thank you very much @marcusg, I am going to review my capistrano config files and tasks and I will keep testing to find what is happening.

**Comment by marcusg** [comment]
@vzamanillo good luck! :+1:

**Comment by marcusg** [comment]
@vzamanillo did you found a solution?

**Comment by vzamanillo** [comment]
Hey Marcus! Not yet, I did not find time to do it. I am going to close the issue at the moment, I will reopen it later if the problem still persist. 

Thank you.

**Comment by vzamanillo** [comment]
@marcusg, I don't know what the problem was but after updating the pg_backup gem and run Capistrano all worked as expected, thank you very much, this pg backup gem is the best and simple postgres backup actually.

**Comment by marcusg** [comment]
@vzamanillo sounds good, thanks!
